[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
test_build_src = yes
lib_deps =
  h2zero/NimBLE-Arduino @ ^2.3.6
build_flags =
  -D BT_PRINT_DEFAULT_PRINTER_BAUD=19200

[env:native]
platform = native
build_flags =
  -D BT_PRINT_DEFAULT_PRINTER_BAUD=19200
  -std=c++17
build_src_filter =
  +<ble_protocol.cpp>
  +<transfer_session.cpp>
test_build_src = yes
test_framework = unity
